/**
 *
 *  TransactionRecords.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace stock_lab
{

class TransactionRecords
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _user_id;
        static const std::string _plan_id;
        static const std::string _symbol;
        static const std::string _action;
        static const std::string _filled_qty;
        static const std::string _filled_price;
        static const std::string _filled_amount;
        static const std::string _commission;
        static const std::string _filled_datetime;
        static const std::string _remark;
        static const std::string _deleted;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit TransactionRecords(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit TransactionRecords(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    TransactionRecords(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    TransactionRecords() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const int64_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const int64_t &pUserId) noexcept;

    /**  For column plan_id  */
    ///Get the value of the column plan_id, returns the default value if the column is null
    const int64_t &getValueOfPlanId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getPlanId() const noexcept;
    ///Set the value of the column plan_id
    void setPlanId(const int64_t &pPlanId) noexcept;

    /**  For column symbol  */
    ///Get the value of the column symbol, returns the default value if the column is null
    const std::string &getValueOfSymbol() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSymbol() const noexcept;
    ///Set the value of the column symbol
    void setSymbol(const std::string &pSymbol) noexcept;
    void setSymbol(std::string &&pSymbol) noexcept;

    /**  For column action  */
    ///Get the value of the column action, returns the default value if the column is null
    const std::string &getValueOfAction() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAction() const noexcept;
    ///Set the value of the column action
    void setAction(const std::string &pAction) noexcept;
    void setAction(std::string &&pAction) noexcept;

    /**  For column filled_qty  */
    ///Get the value of the column filled_qty, returns the default value if the column is null
    const std::string &getValueOfFilledQty() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFilledQty() const noexcept;
    ///Set the value of the column filled_qty
    void setFilledQty(const std::string &pFilledQty) noexcept;
    void setFilledQty(std::string &&pFilledQty) noexcept;

    /**  For column filled_price  */
    ///Get the value of the column filled_price, returns the default value if the column is null
    const std::string &getValueOfFilledPrice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFilledPrice() const noexcept;
    ///Set the value of the column filled_price
    void setFilledPrice(const std::string &pFilledPrice) noexcept;
    void setFilledPrice(std::string &&pFilledPrice) noexcept;

    /**  For column filled_amount  */
    ///Get the value of the column filled_amount, returns the default value if the column is null
    const std::string &getValueOfFilledAmount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFilledAmount() const noexcept;
    ///Set the value of the column filled_amount
    void setFilledAmount(const std::string &pFilledAmount) noexcept;
    void setFilledAmount(std::string &&pFilledAmount) noexcept;

    /**  For column commission  */
    ///Get the value of the column commission, returns the default value if the column is null
    const std::string &getValueOfCommission() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCommission() const noexcept;
    ///Set the value of the column commission
    void setCommission(const std::string &pCommission) noexcept;
    void setCommission(std::string &&pCommission) noexcept;

    /**  For column filled_datetime  */
    ///Get the value of the column filled_datetime, returns the default value if the column is null
    const ::trantor::Date &getValueOfFilledDatetime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getFilledDatetime() const noexcept;
    ///Set the value of the column filled_datetime
    void setFilledDatetime(const ::trantor::Date &pFilledDatetime) noexcept;

    /**  For column remark  */
    ///Get the value of the column remark, returns the default value if the column is null
    const std::string &getValueOfRemark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRemark() const noexcept;
    ///Set the value of the column remark
    void setRemark(const std::string &pRemark) noexcept;
    void setRemark(std::string &&pRemark) noexcept;
    void setRemarkToNull() noexcept;

    /**  For column deleted  */
    ///Get the value of the column deleted, returns the default value if the column is null
    const int8_t &getValueOfDeleted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getDeleted() const noexcept;
    ///Set the value of the column deleted
    void setDeleted(const int8_t &pDeleted) noexcept;
    void setDeletedToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<TransactionRecords>;
    friend drogon::orm::BaseBuilder<TransactionRecords, true, true>;
    friend drogon::orm::BaseBuilder<TransactionRecords, true, false>;
    friend drogon::orm::BaseBuilder<TransactionRecords, false, true>;
    friend drogon::orm::BaseBuilder<TransactionRecords, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<TransactionRecords>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> userId_;
    std::shared_ptr<int64_t> planId_;
    std::shared_ptr<std::string> symbol_;
    std::shared_ptr<std::string> action_;
    std::shared_ptr<std::string> filledQty_;
    std::shared_ptr<std::string> filledPrice_;
    std::shared_ptr<std::string> filledAmount_;
    std::shared_ptr<std::string> commission_;
    std::shared_ptr<::trantor::Date> filledDatetime_;
    std::shared_ptr<std::string> remark_;
    std::shared_ptr<int8_t> deleted_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        sql += "plan_id,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        if(dirtyFlag_[3])
        {
            sql += "symbol,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "action,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "filled_qty,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "filled_price,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "filled_amount,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "commission,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "filled_datetime,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "remark,";
            ++parametersCount;
        }
        sql += "deleted,";
        ++parametersCount;
        if(!dirtyFlag_[11])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[13])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[11])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[12])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace stock_lab
} // namespace drogon_model
